#!/bin/bash

if [ ! -d ../.build-info/src/${1} ];then
  mkdir -p ../.build-info/src/${1}
 else
  /bin/cp ../.build-info/src/${1}/* ./
fi;

make patch

cp *.tar.* ../.build-info/src/${1}/

for dpatch in gcc6;do
  echo "Applying distrotech ${dpatch} patch"
  patch -p1 -N -s -r - -i ../.build-info/distrotech-icedtea8-${dpatch}.patch
done

mkdir -p bootstrap/boot/jre/lib
