#!/bin/bash

if [ -d ${3} ]  && [ "${3}" != "/" ];then
  rm -rf ${3}
fi;

mkdir -p ${3}/usr/${B_LIBDIRS}/jvm/

rsync -avP openjdk.build/images/j2re-image/ ${3}/usr/${B_LIBDIRS}/jvm/jre-${JAVA8_VER}/
rsync -avP openjdk.build/images/j2sdk-image/ ${3}/usr/${B_LIBDIRS}/jvm/jdk-${JAVA8_VER}/

ln -srf ${3}/etc/ssl/certs/java/cacerts ${3}/usr/${B_LIBDIRS}/jvm/jre-${JAVA8_VER}/lib/security/cacerts
ln -srf ${3}/etc/ssl/certs/java/cacerts ${3}/usr/${B_LIBDIRS}/jvm/jdk-${JAVA8_VER}/jre/lib/security/cacerts
